version: "3.9"

services:
  add:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - siterecipe.wsgi:application
      - --bing
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json_file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./siteresipe/database:/app/database