# Generated by Django 5.1.4 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['ingredient_name']},
        ),
        migrations.AddField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
