# Generated by Django 5.1.4 on 2025-01-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_ingredients_options_ingredients_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
