# Generated by Django 5.1.4 on 2025-01-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0009_alter_category_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.recipebase')),
            ],
        ),
        migrations.AddField(
            model_name='recipebase',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipe', through='recipeapp.RecipeIngredients', to='recipeapp.ingredients'),
        ),
    ]
