# Generated by Django 5.1.4 on 2025-01-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_alter_unitmeasure_unit_measure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.recipebase')),
                ('unit_measurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.unitmeasure')),
            ],
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipe', through='recipeapp.Composition', to='recipeapp.ingredients'),
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
