# Generated by Django 5.1.4 on 2025-01-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0013_composition_alter_recipebase_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
