# Generated by Django 5.1.4 on 2025-01-29 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0014_remove_ingredients_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipeapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='cooking_description',
            field=models.TextField(blank=True, verbose_name='Пошаговый рецепт'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipe', through='recipeapp.Composition', to='recipeapp.ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='recipe_title',
            field=models.CharField(max_length=255, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='recipebase',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
